### ISSUE TITLE
Default window size could be improved

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/firmware-updater#135]
![grafik](https://user-images.githubusercontent.com/15329494/202924292-a1cf7484-23b5-4b08-bfa6-cd2281d0d349.png)
maybe something  more like this

![grafik](https://user-images.githubusercontent.com/15329494/202924347-66a95781-7d8c-4e29-8965-2f200f82ec18.png)

**Comment by d-loose** [comment]
I agree - it's too large atm
