### ISSUE TITLE
Should we use YaruWindowTitleBar?

### ISSUE THREAD

**Issue by jpnurmi** [canonical/firmware-updater#154]
I'm not sure if replacing `GtkHeaderBar` by `YaruWindowTitleBar` alone is worth it but perhaps we could make better use of the window title bar if we used the Flutter-based one?

| GtkHeaderBar | YaruTitleBar |
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/220089284-da5248b5-5dd8-46a6-a8f9-9f038e7966b1.png) | ![image](https://user-images.githubusercontent.com/140617/220089045-2fb8f5e9-ae35-4c07-ad04-6585c70f6689.png) |

**Comment by jpnurmi** [comment]
For example:
![image](https://user-images.githubusercontent.com/140617/220092535-6fb7003e-418c-4ccb-9bbe-52c4228344db.png)

**Comment by jpnurmi** [comment]
P.S. I took a shortcut and ignored the battery warning banner because with this structure we cannot easily have it on both sides of master-detail and between title and content, at the same time. Perhaps we could move it to the bottom, though?

![image](https://user-images.githubusercontent.com/140617/220095010-d8b2e249-22f1-478b-b776-c35fffafa416.png)

**Comment by d-loose** [comment]
Yes, I think it looks much better like this!

**Comment by d-loose** [comment]
One issue I found while playing around with this: how do we navigate back in the portrait layout? Intuitively I'd expect a back button as a leading widget in the title bar, but this requires access to the MD page's navigator.

[Screencast from 2023-02-22 11-58-57.webm](https://user-images.githubusercontent.com/113362648/220601182-2d46ac1b-0ac0-4d6d-b8b1-d0bfaf4934e1.webm)

**Comment by Feichtmeier** [comment]
Oh dear 😸 

I think we are facing a similar issue like in software. I could propopse to use the same layout as in Software which is aestecially pleasing but makes the code complicated again. At least it provides a back button
