### ISSUE TITLE
Missing dock and alt-tab icon

### ISSUE THREAD

**Issue by tim-hm** [canonical/firmware-updater#180]
## Background

When running firmware-updater on lunar the dock and super+tab icons are missing (I can't capture a screenshot of the super+tab).

- I am running the firmware-updater from latest/edge `0+git.60bef69 2023-06-03`
- I am on lunar lobster

## Missing Icon In Dock

![image](https://github.com/canonical/firmware-updater/assets/1335525/69a4aa86-e48a-4285-bf5c-3d3ee4f29a24)

**Comment by jbicha** [comment]
@kenvandine Just a reminder that this is still an issue with Ubuntu 23.10

**Comment by tim-hm** [comment]
@d-loose can you add this to your backlog?

**Comment by d-loose** [comment]
Let's wait for @kenvandine's reply - I talked with him about this before and he said he'd look into it, since it's a somewhat tricky xdg icon naming issue

**Comment by kenvandine** [comment]
@sergio-costas can you please take a look at this?  It's happening because there's a shell script that launches it via gapplication and I wasn't able to figure out why it doesn't match an icon.  I guess it has something to do with the Exec not matching the process that's running?

**Comment by sergio-costas** [comment]
I'll check it.

**Comment by sergio-costas** [comment]
Finally, found how to fix it. Sending a patch.
