### ISSUE TITLE
Add links to readme file

### ISSUE THREAD

**Issue by guyluz11** [canonical/firmware-updater#20]
I just came across this repo and was wondering how can I download this tool.

As far as I understand I can find it in the snap store, so adding a link to the snap store could improve the readme file.

Is that the correct snap?
https://snapcraft.io/universal-update-utility

**Comment by guyluz11** [comment]
I can do that if needed.
Just tell me if so and verify that this is the correct link

**Comment by jpnurmi** [comment]
The correct link is https://snapcraft.io/firmware-updater. We could have a badge: https://github.com/snapcore/snap-store-badges
