### ISSUE TITLE
Firmware-updater can't reboot the system

### ISSUE THREAD

**Issue by sergio-costas** [canonical/firmware-updater#207]
Today there was an update for my system, and firmware-updater asked to reboot. I pressed "Reboot" and I received this error:

![Captura desde 2023-10-11 15-07-30](https://github.com/canonical/firmware-updater/assets/105285003/cffe0ce1-747e-4dbd-a99b-d8b834d7f2e3)

It seems that firmware-updater snap lacks the shutdown interface: https://snapcraft.io/docs/shutdown-interface

**Comment by sergio-costas** [comment]
Also, it seems to use a different DBus interface: while the "shutdown" interface uses the "org.freedesktop.login1.Manager" interface in the system bus, firmware-updater wants to use the "org.gnome-SessionManager" interface in the session bus.

**Comment by sergio-costas** [comment]
So there are two possibilities:

* either change the shutdown method in firmware-updater to use the "org.freedesktop.login1.Manager" interface
* or modify snapd to also allow to access the org.gnome.SessionManager interface when the "shutdown" interface is connected

In any case, it will be required to add the "shutdown" plug to firmware-updater, and also request to the snap store to grant the automatic connection of this interface.

**Comment by d-loose** [comment]
Ah, forgot to close this issue as well - fixed in #206.

**Comment by sergio-costas** [comment]
No, you didn't forget; I filled it just ten minutes ago :-D

Thanks.

**Comment by d-loose** [comment]
Ah, sorry too many issues, I got confused :D

**Comment by d-loose** [comment]
> In any case, it will be required to add the "shutdown" plug to firmware-updater, and also request to the snap store to grant the automatic connection of this interface.

This is an important point though - I just tested the latest snap in the candidate channel, and the `shutdown` plug doesn't automatically connect. Could you request this?

**Comment by sergio-costas** [comment]
Mmm... but the snap doesn't have the "shutdown" plug... And if the "fwupd" plug already includes access to that DBus interface, then it's not needed.

**Comment by d-loose** [comment]
I've added the `shutdown` plug in #206. As far as I understand the `fwupd` only works if the corresponding slot is provided by a snap, which isn't the case yet (see details and links in #206).

**Comment by sergio-costas** [comment]
Oh, my fault.

**Comment by sergio-costas** [comment]
Request sent: https://forum.snapcraft.io/t/request-for-firmware-update-shutdown-plug-autoconnection/37270

**Comment by d-loose** [comment]
Thank you :)

**Comment by Feichtmeier** [comment]
This worked for me when I switched to the latest edge channel with the reboot
👍

**Comment by d-loose** [comment]
Thanks for confirming!
Resolved by #206.
