### ISSUE TITLE
UI is cutoff on reboot prompt

### ISSUE THREAD

**Issue by superm1** [canonical/firmware-updater#210]
When installing an update that requires a reboot, it seems that the text is cutoff in the reboot prompt.

![Screenshot from 2023-10-11 12-24-40](https://github.com/canonical/firmware-updater/assets/494526/b0c4cd7f-48f9-4b12-b22d-48af374ff9a0)

**Comment by superm1** [comment]
Looking at bugs I guess this gets closed by this PR: https://github.com/canonical/firmware-updater/pull/208.  Feel free to close if so.

**Comment by d-loose** [comment]
Thanks - yes #208 should fix that :)
