### ISSUE TITLE
Wrong icon display in update modal

### ISSUE THREAD

**Issue by tim-hm** [canonical/firmware-updater#243]
In https://github.com/canonical/firmware-updater/pull/235 the intended icon for the update modal is an arrow pointing up, but in `latest/candidate: 0+git.bb697f9 2023-12-12 (119) 11MB -` I'm seeing a `?`.

![Screenshot from 2023-12-13 10-24-32](https://github.com/canonical/firmware-updater/assets/1335525/66b6eed4-fc8d-4f2d-92a4-14d04097db3c)

**Comment by BLKKKBVSIK** [comment]
fixed in #244
