### ISSUE TITLE
User agent doesn't report to LVFS correctly

### ISSUE THREAD

**Issue by superm1** [canonical/firmware-updater#297]
The LVFS web service has requirements for clients to report their user agents in a structured fashion and to include specific information.  Those requirements are summarized [here](https://lvfs.readthedocs.io/en/latest/download.html).  The reasons for those requirements are also at the same link.

Firmware-updater is an outlier that is not obeying the requirements and is only reporting the user agent:

```
firmware-updater
```

Normally a user agent will report:
* client name, e.g. gnome-software/46.2
* system description, e.g. Linux x86_64
* user language, e.g. en-US
* operating system, e.g. Fedora Linux 40
* the fwupd daemon runtime version, e.g. fwupd/1.9.21

If this isn't solved; then LVFS may eventually block the firmware-updater user agent string.

**Comment by superm1** [comment]
@d-loose can you please fix this?  Like I said LVFS is going to cut off non structured user agents and it will totally break this client.

**Comment by d-loose** [comment]
Thanks for the ping - will take a look this week!
