### ISSUE TITLE
Suggestion: use an Elevated Button if there is an upgrade available

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/firmware-updater#4]
![grafik](https://user-images.githubusercontent.com/15329494/151793949-dd195b80-7b4f-48a5-8c0a-87f9c25e5fac.png)

I think it would be nice to forward the hasUpgrade bool to the buttons and then use an elevated button instead of the outlined button, WDYT @jpnurmi ?

**Comment by jpnurmi** [comment]
I like the idea even though should it be in the dialog because there can be multiple releases available?

**Comment by Feichtmeier** [comment]
The green pill suggests "nice you have an update here that's a good thing". Then you expand the tile and the two buttons are kind of hiding by their wording and subtle visuals that you can open the actual dialog right here. Maybe the wording can be changed to "manage upgrades" and inside the dialog the update tile is also somehow marked to be more engaging?

**Comment by jpnurmi** [comment]
Yes, makes sense to draw the user's attention. Upgrading is the main use-case for this app after all. :)

By the way, there are probably more buttons/actions required. I think those are "utility" types of actions, though, similarly to the verify button. Perhaps they could be moved out of the way into a ⚙ popup menu button...
