### ISSUE TITLE
Master-detail layout

### ISSUE THREAD

**Issue by jpnurmi** [canonical/firmware-updater#43]
![image](https://user-images.githubusercontent.com/140617/189624015-85fde791-ee9e-4046-91b7-41811886be64.png)
![image](https://user-images.githubusercontent.com/140617/189624194-d3f833ab-d386-4682-a2f4-3f81730173a3.png)
![image](https://user-images.githubusercontent.com/140617/189624311-4088e6ab-0c71-4511-b2c9-d007f32fd3e9.png)

Screenshots from https://miro.com/app/board/uXjVO8s0uD4= (not public, sorry)

**Comment by Feichtmeier** [comment]
Is the navigation like chronological steps or a normal master details view?

**Comment by jpnurmi** [comment]
Master-detail with "nested" navigation in the details view to replace the current popup dialog.

**Comment by Feichtmeier** [comment]
Nested navigation sounds nice. Could help with the software app to replace the Dialogs with routes

**Comment by jpnurmi** [comment]
#48 took `YaruMasterDetailPage` into use
