### ISSUE TITLE
Snap: not updated?

### ISSUE THREAD

**Issue by fthx** [canonical/firmware-updater#64]
Hi all,

Will this snap app be soon updated?
Snap version is 8 months old, I don't know if it's about to be updated or just not a goal at the moment.

**Comment by jpnurmi** [comment]
ping @kenvandine

```
  latest/edge:      0+git.55848e6 2022-01-31 (2) 10MB -
```

**Comment by kenvandine** [comment]
Automated builds have been enabled and will be published soon.

**Comment by fthx** [comment]
I can see the new one in snap repo. Thanks!
