### ISSUE TITLE
BackButton could have a better form

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/firmware-updater#70]
The back button for nested pages is a squeezed pill (prbly caused by the reduced appbar height in yaru.dart...)
![grafik](https://user-images.githubusercontent.com/15329494/191720996-60ae273d-4eba-4daf-a3ae-3cd95062340d.png)

A solution would be to put it inside an InkWell instead of an IconButton
![grafik](https://user-images.githubusercontent.com/15329494/191720898-46d3391a-39a9-42a7-ab00-f7120fb2148e.png)

**Comment by jpnurmi** [comment]
hmm, perhaps we could also set `elevation: 0` to remove that extra line until scrolled under?

**Comment by Feichtmeier** [comment]
This un-even circle (alias... ellipse :D ) looks a bit lost in this corner of two lines nonetheless IMO. The appbar border would not change this I think
