### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by jpnurmi** [canonical/firmware-updater#82]
- desired default size?
- reasonable minimum size?
- allow master-detail portrait layout?

[master-detail.webm](https://user-images.githubusercontent.com/140617/192790695-222a1be0-3cfa-4c2b-9f4c-04b48be54fc1.webm)

**Comment by elioqoshi** [comment]
Not sure of the implications of this but a good default size would be similar to the standard file manager window default size.

Minimum size should be the width of the sidebar I'd say.

> allow master-detail portrait layout?

Not sure what that means.
